services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  api-java:
    build:
      context: ../services/api-java
    container_name: api-java
    ports:
      - "8080:8080"
    depends_on:
      - core-python
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  core-python:
    build:
      context: ../services/core-python
    container_name: core-python
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
